# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - af-test-webapp1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://afreg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7825c16ecc724a2ca5e862ef3f55c169 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6491b0249fc941e8b75b86050143ddea }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: afreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7825c16ecc724a2ca5e862ef3f55c169 }}/aftestapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'af-test-webapp1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_25e5969b41f54a0e8d998797eb9c4979 }}
        images: 'afreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7825c16ecc724a2ca5e862ef3f55c169 }}/aftestapp:${{ github.sha }}'